(()=>{const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],modal=$("#leadModal"),form=$("#leadForm"),WA="56941239698";if(!modal||!form)return;const p=new URLSearchParams(location.search),src=p.get("utm_source")||(document.referrer?new URL(document.referrer).hostname:"direct"),med=p.get("utm_medium")||"none",camp=p.get("utm_campaign")||"",landing=location.pathname+location.search;window.dataLayer=window.dataLayer||[];const track=(event,data={})=>window.dataLayer.push({event,timestamp:new Date().toISOString(),source:src,medium:med,campaign:camp,landing,...data});track("commercial_page_view");let intent="contacto";function open(i,preset=""){intent=i;form.elements.intent.value=i;form.elements.source.value=src;form.elements.medium.value=med;form.elements.campaign.value=camp;form.elements.landing.value=landing;if(preset){let o=[...form.elements.need.options].find(x=>x.text.toLowerCase()===preset.toLowerCase());if(o)form.elements.need.value=o.value}modal.classList.add("is-open");modal.setAttribute("aria-hidden","false");setTimeout(()=>form.elements.name.focus(),50);track("lead_form_open",{intent:i})}function close(){modal.classList.remove("is-open");modal.setAttribute("aria-hidden","true")}$$("[data-lead-intent]").forEach(a=>a.addEventListener("click",e=>{e.preventDefault();open(a.dataset.leadIntent,a.dataset.service||a.dataset.offer||"")}));$$("[data-lead-close]").forEach(a=>a.addEventListener("click",close));document.addEventListener("keydown",e=>{if(e.key==="Escape")close()});form.addEventListener("submit",async e=>{e.preventDefault();if(!form.reportValidity())return;const d=Object.fromEntries(new FormData(form).entries()),lead={...d,id:"LEAD-"+Date.now().toString(36).toUpperCase(),created_at:new Date().toISOString(),status:"Nuevo",priority:"Media",next_action:"Contactar",next_action_date:"",notes:"",owner:"Somos Software"};const arr=JSON.parse(localStorage.getItem("somos_leads_pending")||"[]");arr.unshift(lead);localStorage.setItem("somos_leads_pending",JSON.stringify(arr.slice(0,500)));
      // B9.4: if Supabase is configured, also centralize the lead. Local storage remains the fallback.
      try{
        const cfg=window.SOMOS_SUPABASE||{};
        if(cfg.enabled&&cfg.url&&cfg.anonKey&&!cfg.anonKey.includes("YOUR_")){
          const mod=await import("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm");
          const client=mod.createClient(cfg.url,cfg.anonKey);
          const payload={...lead,external_id:lead.id,state:lead.state||lead.status||"Nuevo",next_date:lead.next_date||lead.next_action_date||null}; delete payload.id; delete payload.status; delete payload.next_action_date;
          const {error}=await client.from("leads").insert(payload);
          if(!error)localStorage.setItem("somos_leads_pending",JSON.stringify(arr.filter(x=>x.id!==lead.id)));
          else console.warn("CRM central no disponible; se conserva lead local.",error);
        }
      }catch(err){console.warn("Supabase no disponible; se conserva lead local.",err)}
      track("lead_created",{need:d.need,intent});const msg=["Hola, Somos Software.","",`Nombre: ${d.name}`,`Empresa/actividad: ${d.business||"No indicado"}`,`Contacto: ${d.contact}`,`Necesidad: ${d.need}`,`Plazo: ${d.timeline||"No indicado"}`,`Presupuesto: ${d.budget||"No indicado"}`,`Mensaje: ${d.message}`,`Origen: ${src}`].join("\n");window.open("https://wa.me/"+WA+"?text="+encodeURIComponent(msg),"_blank","noopener");form.reset();close()});$$('a[href*="instagram.com"]').forEach(a=>a.addEventListener("click",()=>track("social_click",{network:"instagram"})));$$('a[href*="facebook.com"]').forEach(a=>a.addEventListener("click",()=>track("social_click",{network:"facebook"})));})();